### ISSUE TITLE
TestResultsPerDate containing 01.01.1999

### ISSUE THREAD

**Issue by eladden** [erasta/CovidDataIsrael#32]
There is a line with the date 01.01.1999. This makes the time axis too long, causing the tests in 2020 to be unreadable. In my opinion, that line should either be removed or ignored.

**Comment by erasta** [comment]
Thank you for raising the issue.
I saw it and it is received like that from MOH, as the tests that was probably done at the beginning, when no dates were registered.
I think ignoring it is problematic as data is lost (the total amount of tests).
But Setting it to something before the first test would be sufficient.
On another similar case i set empty dates to 1.1.2020

**Comment by erasta** [comment]
fixed
