### ISSUE TITLE
Add R graph

### ISSUE THREAD

**Issue by EladHeller** [erasta/CovidDataIsrael#40]

**Comment by erasta** [comment]
@EladHeller could you please elaborate the exact formula of R?
can't find the original discussion on fb.
thank you

**Comment by EladHeller** [comment]
I think the formula is something like this:
The amount of positive tests in the last seven days divided by the amount of positive tests in the seven days preceding them.
For example: the amount of positive tests in 14.10-20.10 was 9242 and in 7.10-13.10 the amount was positive tests was 18926.
9242 divided by 18926 is 0.488.

![R chart](https://user-images.githubusercontent.com/15896603/96840492-304b1480-1453-11eb-8a88-97550eb7bf5c.png)

**Comment by erasta** [comment]
ok
I would expect that on the first days of February it would be infinity, is that correct? 
This can be computed also for each city i presume.

**Comment by erasta** [comment]
done on http://covid.eran.dev/?sheet=testResultsPerDate
