### ISSUE TITLE
Remove dirty data

### ISSUE THREAD

**Issue by EladHeller** [erasta/CovidDataIsrael#41]
In https://covid.eran.dev/?sheet=testResultsPerDate - until 11.2 there is dirty data:
* Negative amount of positive results. 
* Tests before there was any corona tests in the world.

I think the right solution is to drop all data before 12.2.

**Comment by erasta** [comment]
already done, the negative data is real and received as is from moh.
however when you trim the graph using the time slider, the y-axis adapts accordingly.
![image](https://user-images.githubusercontent.com/7118772/96993576-2c42f380-1534-11eb-9a6d-dc31912a4655.png)
