### ISSUE TITLE
Vaccinations per age complete time-series (feature request)

### ISSUE THREAD

**Issue by lucasrodes** [erasta/CovidDataIsrael#52]
Hi @erasta ,
Coming here from https://github.com/owid/covid-19-data/issues/1985. I am trying to add vaccination age data from Israel to our global dataset and was wondering if you have any plans to have a single file with all the time-series data for `vaccinationsPerAge`.

This would facilitate our work a lot, as otherwise, we have to download all `vaccinationsPerAge.csv` files for all https://github.com/erasta/CovidDataIsrael/tree/master/out/history folders.

Kind regards and thanks for your work and help!

**Comment by lucasrodes** [comment]
Found your source: https://github.com/dancarmoz/israel_moh_covid_dashboard_data/blob/master/vaccinated_by_age.csv, which should suffice our needs.

Thanks!

**Comment by erasta** [comment]
Hi @lucasrodes, great to hear about your effort and if you need some more assistance, please contact me.
Both datasets take the data from the same source (ministry of health).
While the excellent @dancarmoz do some backend manipulations to flatten it, i keep all the data in raw csv form to allow more flexible manipulations on the frontend.
Best regards!
